title: "Tech with Thiru"
description: "Resume of Thirunarayanan Sowrirajan - Solutions Architect, Developer, and Tech Enthusiast"
theme: jekyll-theme-midnight
domain: techwiththiru.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://techwiththiru.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /architect/jekyll      # place folder name if the site is served in a subfolder
permalink: pretty
